# Generated by Django 5.0.2 on 2024-03-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingApp', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='avgRatng',
            new_name='avgRating',
        ),
    ]
